hostname: mui.mydomain
moderator_domain: mui.mydomain
backups:
  - { tgz: "/altroot/root.tgz", src: '/root' }
  - { tgz: "/altroot/etc.tgz", src: '/etc'  }
  - { tgz: "/altroot/varcron.tgz", src: '/var/cron'  }
  - { tgz: "/altroot/home.tgz", src: '/home'  }

REPO: "/home/moderatorUI/{{moderator_domain}}"