hostname: pui.mydomain
offense_domain: pui.mydomain
backups:
  - { tgz: "/altroot/root.tgz", src: '/root' }
  - { tgz: "/altroot/etc.tgz", src: '/etc'  }
  - { tgz: "/altroot/varcron.tgz", src: '/var/cron'  }
  - { tgz: "/altroot/var.tgz", src: '/var'  }
  - { tgz: "/altroot/home.tgz", src: '/home'  }

REPO: "/home/participantUI/{{offense_domain}}"