import oracledb from 'oracledb';
import { dbConfig } from '../config.js';
import { platform } from 'os';
oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;

async function connection() {
    // let db="";
    try{
        var db = null;
        db = await oracledb.getConnection(dbConfig);
        console.log("from connection(): trying to connect");
        console.log(((db)?"Database connected!":"Database not connected!"));
        return db;
    }
    catch (e) {
    console.log("ERROR CONNECTING DB: "+e.message);
    throw e;
    // return;
    }
}

async function createTable() {
    let db;
    try{
        db = await connection();
        const sql = `CREATE TABLE TaskList (
            uid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            platform VARCHAR2(15),
            taskURL VARCHAR2(100) NOT NULL,
            taskName VARCHAR2(50) NOT NULL,
            status VARCHAR2(50) DEFAULT 'Pending',
            Note VARCHAR2(300)
        );
        `;
        await db.execute(sql);
        console.log("Table created successfully");
    }
    catch(err){
        console.log("Error creating table, err: "+err.message);
    }
    finally{
        if(db){
            try{await db.close();}
            catch(e){console.error("Error closing db on Create Table: "+e.message);}
        }
    }

}
// Call closePool() when done with application
async function closePool() {
    try {
        await oracledb.getPool().close();
        console.log("Connection pool closed.");
    } catch (err) {
        console.error("Error closing connection pool:", err);
    }
}

export async function getAllTasks() {
    const db = await connection();
    const sql = 'SELECT * FROM TASKLIST'; 
    var TaskList = null;
    try{
        const result = await db.execute(sql);
        TaskList = result.rows;
        console.log("TaskList:"+TaskList);
        // await db.close();
    }catch(err){
        console.log("Error Inserting data: "+ err.message);
        // return null;
    } finally{
        if(db){
            try{await db.close();}
            catch(e){console.log("Error closing DB on Get All Tasks: "+e.message);}
        }
    }
    console.log("Reached end!");
    return TaskList;
}
/*
 Call the function to fetch data
getAllTasks()
  .then((TaskList) => {
    //Process fetched data here or perform other operations
    console.log("Fetched data:", TaskList);
  })
  .catch((err) => {
    console.error("Error:", err);
  });
*/

export async function getTaskByID(taskID) {
    // createTable();   //create table if not exists
    const db = await connection();
    const sql = 'SELECT * FROM TASKLIST WHERE uid = :val1'; 
    try{
        const result = await db.execute(sql, {val1: taskID});
        const TaskList = result.rows;
        console.log("TaskList:\n"+TaskList);
        // await db.close();
        return TaskList;
    }catch(err){
        console.log("Error Inserting data: "+ err.message);
        return null;
    } finally{
        if(db){
            try{await db.close();}
            catch(e){console.log("Error closing DB on Get All Tasks: "+e.message);}
        }
    }
}

export async function addTask(tasks)
{
    var msg={};
    try{
    const db = await connection();
    const sql = 'INSERT INTO TASKLIST (taskName, taskURL, platform) VALUES (:val1, :val2, :val3)';
    const result = await db.execute(sql, 
    {
        val1:tasks.taskName, 
        val2:tasks.taskURL, 
        val3:tasks.platform
    });
    console.log("Inserted data: \n" + result.rowsAffected);
    // await db.close();
    return {message: "Inserted :\n" + tasks};
    // return result.rowsAffected;
    }
    catch(err){
        console.error("Error creating data:", err);
        // await db.close();
        return {error : err.message};
    }finally{
        if(db){
            try{await db.close();}
            catch(e){console.log("Error: "+e.message);}
        }
    }
}
//Update tasks based on uid
export async function updateTask(taskName, taskURL, platform, status, note, uid){
    const query='UPDATE TaskList SET taskName = :val1, taskURL = :val2 , platform = :val3 , status = :val4 , note = :val5 WHERE uid= :val6 ';
    // const any=[taskName,taskURL, platform, uid];
    var msg={};
    const db = await connection();
    try{
        const res = await db.execute(query, {
            val1: taskName,
            val2: taskURL,
            val3: platform,
            val4: status,
            val5: note,
            val6: uid
        });
        console.log("Updated task " + taskName + "And res:\n");
        console.log(res);
        // await db.close();
        return res.rowsAffected;
    }
    catch(e){
        console.error("Error updating data: ", e.message);
        // await db.close();
        return null;
    }
    finally{
        if(db){
            try{await db.close();}
            catch(e){console.log("Error: "+e.message);}
        }
    }
}

export async function deleteTask(taskID) {
    let db;
    const sql = 'DELETE FROM TaskList WHERE uid = :val1 ';
    var errMsg={error:""};
    try{
        db = await connection();
        await db.execute(sql,{val1: taskID});
        // await db.close();
        return {message:"Deleted task with ID " + taskID+"\n"};
    }
    catch(err){
        console.error("Error deleting data:", err.message);
        // await db.close();
        return {error:"ERROR deleting task with ID " + taskID+"\n"};
    }
    finally{
        if(db){
            try{await db.close();}
            catch(e){console.log("Error Closing DB on AddTask: "+e.message);}
        }
    }
    
}
// const cmd_trigger = `CREATE TRIGGER IF NOT EXISTS set_course_id 
//     BEFORE INSERT ON courses
//     BEGIN
//         UPDATE courses
//         SET courseId = NEW.courseId || NEW.uid
//         WHERE rowid = NEW.rowid;
//     END;`;

// createTable();