services:
  webapp:
    hostname: 'rtbdev'
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/home/rtbdev/code/:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      mysql:
        condition: service_healthy
      memcached:
        condition: service_started

  mysql:
    image: mysql:8.0
    hostname: 'mysql'
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --skip-name-resolve=OFF
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -P 3306 | grep 'mysqld is alive' || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 12
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
      - MYSQL_DATABASE=rootthebox
      - MYSQL_USER=rtb
      - MYSQL_PASSWORD=rootthebox
