version: '2'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=mistctf123
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=oracle+cx_oracle://ctfd:ctfd@db:1521/?service_name=XEPDB1
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
      default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  db:
    image: oracle/database:21.3.0-xe
    container_name: oracle_db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=ctfd
      - ORACLE_EDITION=xe
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      default:
        internal: true

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      default:
        internal: true

networks:
  default:

volumes:
  oracle_data:
