#!/usr/bin/env ansible-playbook
---
- name: Build, tag and push docker-target images
  hosts: targets
  gather_facts: false
  serial: 1
  connection: local
  tasks:
  - docker_image:
      name: "{{DOCKER_REGISTRY}}/{{DOCKER_REPOSITORY}}/{{container.name|lower}}"
      tag: "{{container.tag|default('latest')}}"
      state: present
      source: build
      push: "{{force_push|default('yes')}}"
      build:
        path: "../Dockerfiles/{{container.build}}"
        args: "{{container.buildargs|default(omit)}}"
        nocache: yes
        pull: no
      force_source: "{{force_build|default('no')}}"
      force_tag: "{{force_build|default('no')}}"
    when: container is defined and container.build is defined
    delegate_to: "{{BUILDER}}"
