#!/usr/bin/env ansible-playbook
---
- name: Build with squash and tag docker target images
  hosts: all
  gather_facts: false
  serial: 1
  connection: local
  vars:
    string: ""
    pushtag: "{{DOCKER_REGISTRY}}/{{DOCKER_REPOSITORY}}/{{container.name|lower}}{{ ':'+container.tag|default('latest')}}"
  tasks:
  - set_fact:
        string: "{{ string }}{{ (index > 0)|ternary(' ','') }}--build-arg {{ item.key }}='{{ item.value }}'"
    loop: "{{  container.buildargs|default({}) |dict2items }}"
    loop_control:
      index_var: index
    when: container.buildargs is defined
    delegate_to: "{{BUILDER|default('localhost')}}"


  - set_fact:
        command_str: docker build --rm --force-rm --squash -q --no-cache {{string}} . -t "{{DOCKER_REGISTRY}}/{{DOCKER_REPOSITORY}}/{{container.name|lower}}{{ ':'+container.tag|default(omit)}}"
    delegate_to: "{{BUILDER|default('localhost')}}"

  - name: Build image
    command: "{{command_str}}"
    args:
      chdir: "{{ lookup('env', 'PWD')}}/Dockerfiles/{{container.build}}"
    delegate_to: "{{BUILDER|default('localhost')}}"
    tags:
      - build

  - name: Push image
    command: docker push {{pushtag}}
    delegate_to: "{{BUILDER|default('localhost')}}"
    tags:
      - push

  - name: Remove image
    command: docker rmi -f "{{pushtag}}"
    delegate_to: "{{BUILDER|default('localhost')}}"
    tags:
      - rmi
