#!/usr/bin/env ansible-playbook
---
- name: Count treasures per target based on targets host_vars
  hosts: targets
  gather_facts: false
#  serial: 1
  tasks:
#  - name: Count USERS
#    delegate_to: 127.0.0.1
#    ignore_errors: true
#    debug: msg="{{ ansible_host }}:{{ item.username }}:{{ item.password }}"
#    with_items: "{{DETAILS}}"
#    when: DETAILS is defined and item.username != "ETSCTF" and item.password != "*LK*"
#    tags:
#      - UI

  - name: Retrieve username and password records
    delegate_to: 127.0.0.1
    run_once: yes
    template:
        src: ../templates/passwords_challenge.yml
        dest: ../passwords_challenge.yml
